### PR TITLE
change coalescing operator (??) in query and container file

### PR DESCRIPTION
**Pull request by shopifychamp**
I changed coalescing operator (??) to isset, it is because I am using your repo, it works well for version>=7.* but fails for 5.6 or above. Please merge this changes to use your repo for all PHP versions.

### CODE REVIEW

**Comment by rudiedirkx** [comment]
You cannot be using PHP < 7 anymore. There's no excuse.

**Comment by shopifychamp** [comment]
Thank you for your response @rudiedirkx.
Stay safe and healthy :)

**Comment by rudiedirkx** [comment]
Wow, you're very understanding =) You too.

You can use `cweagans/composer-patches` to patch package code, if you use Composer. Perfect for this case.

**Comment by shopifychamp** [comment]
Hi,
Thank you for your reply.
Actually i am using your repo for graphql in my repository. I created sdk
for public and private app for Shopify
<http://github.com/shopifychamp/shopify-private-app-sdk/>. So that i want
if any community member wants to install our repo for 5.6 php version then
it should work.  I am new in github and created my first project then
please feel free to contribute and suggest me any updates.

Thanks
Kshitij Verma

**Pull request closed without merging**
